server {
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /v1/ {
        proxy_pass http://${BACKEND_URL}/v1/;
    }

    location /health {
        proxy_pass http://${BACKEND_URL}/health;
    }

    location /docs {
        proxy_pass http://${BACKEND_URL}/docs;
    }

    location /openapi.json {
        proxy_pass http://${BACKEND_URL}/openapi.json;
    }
}
